// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC37sB-03-9LlYlrsZs1ZdwR_Ue8F9Nhzc',
    appId: '1:803404929042:web:eb9e32659a0f75390660cb',
    messagingSenderId: '803404929042',
    projectId: 'prog-jobs-grad',
    authDomain: 'prog-jobs-grad.firebaseapp.com',
    storageBucket: 'prog-jobs-grad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB56R-ERgMpJG7V9z1ZUCbjBOtsL5FvUJw',
    appId: '1:803404929042:android:53f919ff9a04063e0660cb',
    messagingSenderId: '803404929042',
    projectId: 'prog-jobs-grad',
    storageBucket: 'prog-jobs-grad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdJVtDm56GKlryaFzJX3RxzHtn4ZGUyG4',
    appId: '1:803404929042:ios:ce6905a109c7eb710660cb',
    messagingSenderId: '803404929042',
    projectId: 'prog-jobs-grad',
    storageBucket: 'prog-jobs-grad.appspot.com',
    iosClientId: '803404929042-vn3i4lkv6qob842t4mts981rfnqkgbun.apps.googleusercontent.com',
    iosBundleId: 'com.example.progJobsGrad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdJVtDm56GKlryaFzJX3RxzHtn4ZGUyG4',
    appId: '1:803404929042:ios:ce6905a109c7eb710660cb',
    messagingSenderId: '803404929042',
    projectId: 'prog-jobs-grad',
    storageBucket: 'prog-jobs-grad.appspot.com',
    iosClientId: '803404929042-vn3i4lkv6qob842t4mts981rfnqkgbun.apps.googleusercontent.com',
    iosBundleId: 'com.example.progJobsGrad',
  );
}
